spring.application.name=fleet-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3307/fleet_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update